services:
  - type: web
    name: payrollpro-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install gunicorn
    startCommand: gunicorn --worker-tmp-dir /dev/shm app_backend.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:///data/payroll.db
    disk:
      name: payroll-data
      mountPath: /data
    plan: free  # Remove for production (uses Starter plan)