services:
  - type: web
    name: payrollpro-web
    runtime: python
    pythonVersion: "3.11.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_backend.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:///var/tmp/payroll.db
    plan: free