services:
  - type: web
    name: payrollpro-web
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install gunicorn
    startCommand: gunicorn --worker-tmp-dir /dev/shm app_backend.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:///tmp/payroll.db  # Changed to /tmp
    
    # REMOVED disk section entirely
    plan: free